# Generated by Django 2.0.3 on 2019-10-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=80)),
                ('realname', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=18)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=25)),
                ('jurisdiction', models.CharField(max_length=10)),
            ],
        ),
    ]
